import TestKit

// Entry point for the whole suite. Every new test file adds one `register` call.
// Run with: swift run LumiereTests
@MainActor
func runAll() async {
    let t = TestRunner()

    registerSystemCapabilitiesTests(t)
    registerServerURLNormalizerTests(t)
    registerJellyfinImageURLTests(t)
    registerJellyfinDecodingTests(t)
    registerDownsampleTests(t)
    registerMediaSummaryTests(t)
    registerPlaybackDecisionTests(t)
    registerPlaybackDecisionFallbackTests(t)
    registerStreamBuilderTests(t)
    registerPreferredTracksTests(t)
    registerTrickplayTests(t)
    registerTrickplayCellTests(t)
    registerTitleStyleTests(t)
    registerConnectionStateTests(t)
    registerOfflineModeTests(t)
    registerSyncSelectionTests(t)
    registerAuthHeaderTests(t)
    registerDownloadTests(t)
    registerTrackPreferenceTests(t)
    registerExtrasClassifierTests(t)
    registerPlaylistGroupingTests(t)
    registerMusicPageTests(t)
    registerLatestShelfTests(t)
    registerSpotlightMixTests(t)
    registerSpecialsOrderTests(t)
    registerFranchiseGroupingTests(t)
    registerProseGroupingTests(t)
    registerCreditlessClassifierTests(t)
    registerItemEditTests(t)
    registerEditFieldSetTests(t)
    registerCollectionOrderTests(t)
    registerEpisodeNumberingTests(t)
    registerSubtitleKindTests(t)
    registerSubtitleSizeTests(t)
    registerTimecodeTests(t)
    registerLocalLibraryTests(t)
    registerFilenameFranchiseTests(t)
    registerCollectionDraftTests(t)
    registerAlphabetIndexTests(t)
    registerFolderViewModeTests(t)
    registerStudioFilterTests(t)
    registerLibraryOrderTests(t)
    registerEpisodeStillTests(t)
    registerResumeCutoffTests(t)
    registerRememberedVolumeTests(t)
    registerSettingsPanelSizeTests(t)
    registerIntroLearningTests(t)
    await registerIntroStorageTests(t)
    registerLibraryChangeTests(t)
    registerServerScanWaitTests(t)
    registerSpotlightReasonTests(t)
    registerNewShelfTests(t)
    registerMetadataLineTests(t)
    registerGridKeyboardTests(t)
    registerSearchRankingTests(t)
    registerHomeShelfCapTests(t)
    registerDominantFactTests(t)
    registerMediaSegmentTests(t)
    registerRecentlyAddedPolicyTests(t)
    registerDiscreetArtPolicyTests(t)
    registerHomeHiddenTests(t)
    registerShelfRulesTests(t)
    registerSegmentTrustTests(t)
    registerScrollSeekTests(t)
    registerSeekLandingTests(t)
    registerDiskPlaybackTests(t)
    registerSyncTriggerTests(t)
    registerDetailFreshnessTests(t)
    await registerUnplayedCountTests(t)
    registerEpisodeOrderTests(t)
    registerTypeScaleTests(t)
    registerSearchKeyTests(t)
    registerFilenameEpisodeRepairTests(t)
    registerPathTitleGuessTests(t)
    registerProviderIdMatchTests(t)
    await registerProviderSearchTests(t)
    await registerLibraryDatabaseTests(t)
    await registerLibraryFilterTests(t)
    await registerLibraryFilterTests2(t)
    await registerTopRatedTests(t)
    await registerPlaybackOutboxTests(t)
    await registerScheduledTaskTests(t)
    await registerTopShelfSelectionTests(t)
    await registerFolderTitleTests(t)
    await registerFolderTreeTests(t)
    await registerHomeOrderTests(t)
    await registerMergedFileTests(t)
    await registerLibraryKindsTests(t)
    await registerContentDateTests(t)
    registerLibraryGroupingTests(t)
    await registerOrphanPruneTests(t)
    await registerLocalScanTests(t)
    await registerSyncSweepTests(t)
    await registerImageCacheTests(t)
    await registerMemoryBudgetTests(t)
    await registerWatchObservationTests(t)
    await registerWatchRoundTripTests(t)
    registerFlipMemoryTests(t)
    registerWatchedRuleTests(t)
    registerLibraryHealthTests(t)
    registerSeasonNeighbourTests(t)
    registerPaperThemeTests(t)
    registerFetchedSubtitleTests(t)
    await registerRefreshGateTests(t)
    await registerSeasonlessShowTests(t)
    await registerTimeEntryTests(t)
    await registerAudioOffsetTests(t)
    await registerCollectionSearchTests(t)
    await registerRoomTests(t)
    await registerRoomPreferenceTests(t)
    await registerChangeFeedTests(t)
    await registerPreviewSyncTests(t)
    await registerExtrasGroupingTests(t)

    t.finish()
}

await runAll()
